### PR TITLE
Fix description of main export

### PR DESCRIPTION
**Pull request by vweevers**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] ~~If applicable, I’ve added docs and tests~~

### Description of changes

The description in the jsdoc/tsdoc comment of the main export seems to have been copied from another plugin; this corrects it.

### CODE REVIEW

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
nice catch, thanks!

**Comment by wooorm** [comment]
Thanks Vincent, released!

**Comment by paescuj** [comment]
FYI: It seems like the version `11.2.2` has been published without rebuilding - at least the description is still wrong...

**Comment by wooorm** [comment]
Weird! I cut another release and verified it’s there https://github.com/remarkjs/remark-github/releases/tag/11.2.3

**Comment by paescuj** [comment]
Nice, thanks for the fast reaction!

**Pull request merged**
